"""
Tests for single-track and bulk Artist/Genre editing on managed Inbox
tracks (backend.app.services.workspace_service.edit_inbox_track_metadata,
bulk_edit_preview, bulk_edit_apply) and their routes.

These exercise the real controlled tag-write path (preparation_service.
write_tracks -> tag_write_service.build_plan/apply_plan), so they need real
audio fixtures generated by ffmpeg -- skipped if ffmpeg is unavailable,
matching tests/test_tag_write_service.py's convention. Every fixture lives
under pytest's tmp_path; nothing under /home/paak/Music/crateiq-test-library
is ever touched.
"""
from __future__ import annotations

import shutil
import sqlite3
import subprocess
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import backend.app.core.db as backend_core_db
import backend.app.main as backend_main
from backend.app.services import preparation_service, workspace_service

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not available")


def _make_audio(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
         "-t", "1", "-c:a", "libmp3lame", "-b:a", "32k", str(path)],
        check=True,
    )


def _read_tags(path: Path) -> dict[str, str]:
    from mutagen import File as MFile
    audio = MFile(str(path), easy=True)
    get = lambda k: (audio.get(k) or [""])[0]
    return {k: get(k) for k in ("artist", "title", "genre")}


@pytest.fixture()
def managed_root(tmp_path, monkeypatch):
    root = tmp_path / "managed"
    workspace_service.configure_workspace(root)
    monkeypatch.setenv("CRATEIQ_LIBRARY_ROOT", str(root))
    monkeypatch.setattr(backend_core_db, "JOBS_DB_PATH", tmp_path / "jobs.db")
    backend_core_db.init_db()
    return root


@pytest.fixture()
def client(managed_root):
    test_client = TestClient(backend_main.app)
    with test_client:
        yield test_client, managed_root


def _seed_track(
    root: Path, filename: str, *, zone: str = "INBOX",
    artist: str = "Old Artist", title: str = "Some Title", genre: str = "Dance",
) -> int:
    path = root / ("Inbox" if zone == "INBOX" else "Library") / filename
    _make_audio(path)
    with sqlite3.connect(root / "logs" / "processed.db") as conn:
        conn.execute(
            """INSERT INTO tracks (filepath, filename, artist, title, genre, status,
                                    processed_at, pipeline_ver, storage_zone)
               VALUES (?, ?, ?, ?, ?, 'pending', '2026-01-01T00:00:00Z', 'test', ?)""",
            (str(path), filename, artist, title, genre, zone),
        )
        return conn.execute("SELECT last_insert_rowid()").fetchone()[0]


def _row(root: Path, track_id: int) -> sqlite3.Row:
    with sqlite3.connect(root / "logs" / "processed.db") as conn:
        conn.row_factory = sqlite3.Row
        return conn.execute("SELECT * FROM tracks WHERE id = ?", (track_id,)).fetchone()


# ---------------------------------------------------------------------------
# Single Artist edit
# ---------------------------------------------------------------------------

def test_single_artist_edit_writes_verifies_and_updates_index(managed_root):
    track_id = _seed_track(managed_root, "song.mp3", artist="Old Artist")
    path = managed_root / "Inbox" / "song.mp3"

    result = workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="Black Coffee")

    assert result["status"] == "updated"
    assert result["fields_changed"] == ["artist"]
    assert result["tag_write"]["written_count"] == 1
    assert result["tag_write"]["failed_count"] == 0
    assert _row(managed_root, track_id)["artist"] == "Black Coffee"
    assert _read_tags(path)["artist"] == "Black Coffee", "file tag must be verified-written, not just the index"


def test_single_artist_edit_creates_backup(managed_root):
    track_id = _seed_track(managed_root, "song.mp3", artist="Old Artist")
    result = workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="Black Coffee")

    op_id = result["tag_write"]["results"][0].get("track_id")
    from backend.app.services import tag_write_service
    ops = tag_write_service.list_operations(limit=5)
    assert ops, "a tag-write operation must have been recorded"
    assert ops[0]["backup_manifest"], "a byte-for-byte backup must have been created before the write"


def test_single_genre_edit_writes_verifies_and_updates_index(managed_root):
    track_id = _seed_track(managed_root, "song.mp3", genre="Dance")
    path = managed_root / "Inbox" / "song.mp3"

    result = workspace_service.edit_inbox_track_metadata(managed_root, track_id, genre="Afro House")

    assert result["status"] == "updated"
    assert _row(managed_root, track_id)["genre"] == "Afro House"
    assert _read_tags(path)["genre"] == "Afro House"


def test_edit_rejects_empty_value(managed_root):
    track_id = _seed_track(managed_root, "song.mp3")
    with pytest.raises(ValueError, match="empty"):
        workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="   ")


def test_edit_rejects_non_inbox_track(managed_root):
    track_id = _seed_track(managed_root, "promoted.mp3", zone="LIBRARY")
    with pytest.raises(ValueError, match="Inbox"):
        workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="New")


def test_edit_no_change_when_value_identical(managed_root):
    track_id = _seed_track(managed_root, "song.mp3", artist="Same Artist")
    result = workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="Same Artist")
    assert result["status"] == "no_change"
    assert result["tag_write"] is None


def test_edit_preserves_unicode(managed_root):
    track_id = _seed_track(managed_root, "song.mp3")
    result = workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="Björk")
    assert result["artist"] == "Björk"
    assert _row(managed_root, track_id)["artist"] == "Björk"


def test_edit_external_original_unchanged(tmp_path, managed_root):
    source_file = tmp_path / "downloads" / "Track.mp3"
    _make_audio(source_file)
    original_bytes = source_file.read_bytes()

    workspace_service.import_sources(managed_root, [str(source_file)], confirm=True)
    with sqlite3.connect(managed_root / "logs" / "processed.db") as conn:
        conn.row_factory = sqlite3.Row
        track_id = conn.execute("SELECT id FROM tracks WHERE storage_zone = 'INBOX'").fetchone()["id"]

    workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="New Artist")

    assert source_file.read_bytes() == original_bytes


def test_edit_refreshes_readiness(managed_root):
    track_id = _seed_track(managed_root, "song.mp3", artist="A", title="T", genre="")
    with sqlite3.connect(managed_root / "logs" / "processed.db") as conn:
        conn.execute("UPDATE tracks SET genre = NULL WHERE id = ?", (track_id,))
        conn.commit()

    before = workspace_service.promotion_preview(managed_root, [track_id])["items"][0]
    assert before["ready"] is False
    assert any("Genre" in b for b in before["blockers"])

    workspace_service.edit_inbox_track_metadata(managed_root, track_id, genre="Afro House")

    after = workspace_service.promotion_preview(managed_root, [track_id])["items"][0]
    assert after["ready"] is True


# ---------------------------------------------------------------------------
# HTTP route
# ---------------------------------------------------------------------------

def test_patch_route_edits_artist_and_genre_together(client):
    test_client, root = client
    track_id = _seed_track(root, "song.mp3")

    resp = test_client.patch(
        f"/api/workspace/inbox/tracks/{track_id}", json={"artist": "Black Coffee", "genre": "Afro House"},
    )

    assert resp.status_code == 200
    body = resp.json()
    assert body["metadata"]["status"] == "updated"
    assert set(body["metadata"]["fields_changed"]) == {"artist", "genre"}
    assert _read_tags(root / "Inbox" / "song.mp3") == {"artist": "Black Coffee", "title": "Some Title", "genre": "Afro House"}


def test_patch_route_rejects_blank_artist_with_422(client):
    test_client, root = client
    track_id = _seed_track(root, "song.mp3")
    resp = test_client.patch(f"/api/workspace/inbox/tracks/{track_id}", json={"artist": "   "})
    assert resp.status_code == 422


# ---------------------------------------------------------------------------
# Bulk edit
# ---------------------------------------------------------------------------

def test_bulk_edit_preview_shows_current_values_and_new_value(managed_root):
    ids = [
        _seed_track(managed_root, "a.mp3", genre="Dance"),
        _seed_track(managed_root, "b.mp3", genre="Electro"),
        _seed_track(managed_root, "c.mp3", genre="Afro House"),
    ]
    preview = workspace_service.bulk_edit_preview(managed_root, ids, artist=None, genre="Afro House")

    assert preview["selected_count"] == 3
    assert preview["eligible_count"] == 3
    assert preview["fields"]["genre"]["new_value"] == "Afro House"
    assert set(preview["fields"]["genre"]["current_values"]) == {"Dance", "Electro", "Afro House"}


def test_bulk_edit_preview_requires_at_least_one_field(managed_root):
    ids = [_seed_track(managed_root, "a.mp3")]
    with pytest.raises(ValueError, match="at least one field"):
        workspace_service.bulk_edit_preview(managed_root, ids, artist=None, genre=None)


def test_bulk_edit_preview_requires_selection(managed_root):
    with pytest.raises(ValueError, match="at least one track"):
        workspace_service.bulk_edit_preview(managed_root, [], artist=None, genre="Afro House")


def test_bulk_edit_apply_sets_genre_across_several_tracks(managed_root):
    ids = [_seed_track(managed_root, f"t{i}.mp3", genre="Dance") for i in range(3)]

    result = workspace_service.bulk_edit_apply(managed_root, ids, artist=None, genre="Afro House", confirm=True)

    assert result["selected_count"] == 3
    assert result["changed_count"] == 3
    assert result["succeeded_count"] == 3
    assert result["failed_count"] == 0
    for track_id, filename in zip(ids, ["t0.mp3", "t1.mp3", "t2.mp3"]):
        assert _row(managed_root, track_id)["genre"] == "Afro House"
        assert _read_tags(managed_root / "Inbox" / filename)["genre"] == "Afro House"


def test_bulk_edit_apply_sets_artist_across_several_tracks(managed_root):
    ids = [_seed_track(managed_root, f"t{i}.mp3", artist="Unknown") for i in range(3)]

    result = workspace_service.bulk_edit_apply(managed_root, ids, artist="Black Coffee", genre=None, confirm=True)

    assert result["succeeded_count"] == 3
    for track_id in ids:
        assert _row(managed_root, track_id)["artist"] == "Black Coffee"


def test_bulk_edit_apply_sets_both_fields_in_one_operation(managed_root):
    ids = [_seed_track(managed_root, f"t{i}.mp3") for i in range(2)]

    result = workspace_service.bulk_edit_apply(
        managed_root, ids, artist="Black Coffee", genre="Afro House", confirm=True,
    )

    assert result["succeeded_count"] == 2
    for track_id, filename in zip(ids, ["t0.mp3", "t1.mp3"]):
        row = _row(managed_root, track_id)
        assert row["artist"] == "Black Coffee" and row["genre"] == "Afro House"
        tags = _read_tags(managed_root / "Inbox" / filename)
        assert tags["artist"] == "Black Coffee" and tags["genre"] == "Afro House"


def test_bulk_edit_apply_requires_confirm(managed_root):
    ids = [_seed_track(managed_root, "a.mp3")]
    with pytest.raises(ValueError, match="confirm=true"):
        workspace_service.bulk_edit_apply(managed_root, ids, artist=None, genre="Afro House", confirm=False)


def test_bulk_edit_apply_rejects_no_field_selected(managed_root):
    ids = [_seed_track(managed_root, "a.mp3")]
    with pytest.raises(ValueError, match="at least one field"):
        workspace_service.bulk_edit_apply(managed_root, ids, artist=None, genre=None, confirm=True)


def test_bulk_edit_apply_rejects_empty_selection(managed_root):
    with pytest.raises(ValueError, match="at least one track"):
        workspace_service.bulk_edit_apply(managed_root, [], artist=None, genre="Afro House", confirm=True)


def test_bulk_edit_apply_skips_non_inbox_tracks_truthfully(managed_root):
    inbox_id = _seed_track(managed_root, "inbox.mp3", genre="Dance")
    library_id = _seed_track(managed_root, "promoted.mp3", zone="LIBRARY", genre="Dance")

    result = workspace_service.bulk_edit_apply(
        managed_root, [inbox_id, library_id], artist=None, genre="Afro House", confirm=True,
    )

    assert result["succeeded_count"] == 1
    assert result["skipped_count"] == 1
    by_id = {r["track_id"]: r for r in result["results"]}
    assert by_id[library_id]["status"] == "skipped"
    assert _row(managed_root, library_id)["genre"] == "Dance", "non-Inbox track must never be modified"


def test_bulk_edit_apply_counts_true_no_ops(managed_root):
    already = _seed_track(managed_root, "already.mp3", genre="Afro House")
    changed = _seed_track(managed_root, "changed.mp3", genre="Dance")

    result = workspace_service.bulk_edit_apply(
        managed_root, [already, changed], artist=None, genre="Afro House", confirm=True,
    )

    assert result["unchanged_count"] == 1
    assert result["succeeded_count"] == 1
    by_id = {r["track_id"]: r for r in result["results"]}
    assert by_id[already]["status"] == "unchanged"


def test_bulk_edit_apply_reports_missing_track_truthfully(managed_root):
    inbox_id = _seed_track(managed_root, "inbox.mp3", genre="Dance")
    result = workspace_service.bulk_edit_apply(
        managed_root, [inbox_id, 999999], artist=None, genre="Afro House", confirm=True,
    )
    assert result["not_found_count"] == 1
    assert result["succeeded_count"] == 1


def test_bulk_edit_apply_one_failure_does_not_flip_other_successes(managed_root):
    """An unsupported-format track among the selection must fail independently."""
    good_id = _seed_track(managed_root, "good.mp3", genre="Dance")
    bad_path = managed_root / "Inbox" / "bad.wav"
    bad_path.parent.mkdir(parents=True, exist_ok=True)
    bad_path.write_bytes(b"not real audio")
    with sqlite3.connect(managed_root / "logs" / "processed.db") as conn:
        conn.execute(
            """INSERT INTO tracks (filepath, filename, artist, title, genre, status,
                                    processed_at, pipeline_ver, storage_zone)
               VALUES (?, 'bad.wav', 'A', 'T', 'Dance', 'pending',
                       '2026-01-01T00:00:00Z', 'test', 'INBOX')""",
            (str(bad_path),),
        )
        bad_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    result = workspace_service.bulk_edit_apply(
        managed_root, [good_id, bad_id], artist=None, genre="Afro House", confirm=True,
    )

    by_id = {r["track_id"]: r for r in result["results"]}
    assert by_id[good_id]["status"] == "succeeded"
    assert by_id[bad_id]["status"] == "failed"
    assert result["succeeded_count"] == 1
    assert result["failed_count"] == 1
    assert _row(managed_root, good_id)["genre"] == "Afro House"


def test_bulk_edit_apply_external_originals_unchanged(tmp_path, managed_root):
    source_files = []
    for i in range(3):
        f = tmp_path / "downloads" / f"track{i}.mp3"
        _make_audio(f)
        source_files.append(f)
    originals = {f: f.read_bytes() for f in source_files}

    workspace_service.import_sources(managed_root, [str(f) for f in source_files], confirm=True)
    with sqlite3.connect(managed_root / "logs" / "processed.db") as conn:
        conn.row_factory = sqlite3.Row
        ids = [r["id"] for r in conn.execute("SELECT id FROM tracks WHERE storage_zone = 'INBOX'")]

    workspace_service.bulk_edit_apply(managed_root, ids, artist=None, genre="Afro House", confirm=True)

    for f, original in originals.items():
        assert f.read_bytes() == original


def test_bulk_edit_apply_refreshes_readiness(managed_root):
    ids = [_seed_track(managed_root, f"t{i}.mp3", genre="") for i in range(2)]
    with sqlite3.connect(managed_root / "logs" / "processed.db") as conn:
        conn.execute(f"UPDATE tracks SET genre = NULL WHERE id IN ({','.join('?' * len(ids))})", ids)
        conn.commit()

    before = workspace_service.promotion_preview(managed_root, ids)
    assert before["ready_count"] == 0

    workspace_service.bulk_edit_apply(managed_root, ids, artist=None, genre="Afro House", confirm=True)

    after = workspace_service.promotion_preview(managed_root, ids)
    assert after["ready_count"] == 2


# ---------------------------------------------------------------------------
# HTTP routes for bulk edit
# ---------------------------------------------------------------------------

def test_bulk_edit_preview_route(client):
    test_client, root = client
    ids = [_seed_track(root, f"t{i}.mp3", genre="Dance") for i in range(3)]

    resp = test_client.post("/api/workspace/inbox/bulk-edit/preview", json={"track_ids": ids, "genre": "Afro House"})

    assert resp.status_code == 200
    assert resp.json()["selected_count"] == 3


def test_bulk_edit_apply_route_requires_confirm(client):
    test_client, root = client
    ids = [_seed_track(root, "a.mp3")]
    resp = test_client.post("/api/workspace/inbox/bulk-edit/apply", json={"track_ids": ids, "genre": "Afro House"})
    assert resp.status_code == 422


def test_bulk_edit_apply_route_applies_with_confirm(client):
    test_client, root = client
    ids = [_seed_track(root, f"t{i}.mp3", artist="Old") for i in range(3)]

    resp = test_client.post(
        "/api/workspace/inbox/bulk-edit/apply",
        json={"track_ids": ids, "artist": "Black Coffee", "confirm": True},
    )

    assert resp.status_code == 200
    body = resp.json()
    assert body["succeeded_count"] == 3


# ---------------------------------------------------------------------------
# Manual-edit precedence regression (section 9)
# ---------------------------------------------------------------------------

def test_manual_artist_survives_process_all_enrich(managed_root, monkeypatch):
    track_id = _seed_track(managed_root, "song.mp3", artist="Old Artist", title="A Title", genre="")
    workspace_service.edit_inbox_track_metadata(managed_root, track_id, artist="My Deliberate Artist")

    def _fake_gather_evidence(*args, **kwargs):
        raise AssertionError("must not be called when nothing is junk/empty for this track")

    # Genre is still empty so the track remains eligible for enrichment
    # consideration, but the manually-set Artist is non-empty and non-junk,
    # so the existing "never overwrite existing non-empty data" rule in
    # preparation_service.enrich_tracks must leave it exactly as-is even if
    # a provider strongly disagrees.
    from backend.app.services import provider_routing_service, consensus_service

    class _FieldConsensus:
        def __init__(self, value, confidence):
            self.value = value
            self.confidence = confidence
            self.reason_code = "matched"
            self.evidence = []

    class _Consensus:
        fields = {
            "artist": _FieldConsensus("Someone Else Entirely", "HIGH"),
            "title": _FieldConsensus(None, "LOW"),
            "genre": _FieldConsensus("Afro House", "HIGH"),
        }

    monkeypatch.setattr(provider_routing_service, "gather_evidence", lambda *a, **k: {})
    monkeypatch.setattr(consensus_service, "build_track_consensus", lambda *a, **k: _Consensus())

    preparation_service.enrich_tracks(managed_root, [track_id])

    assert _row(managed_root, track_id)["artist"] == "My Deliberate Artist", (
        "a manually-entered non-empty, non-junk Artist must survive Process All's enrichment stage"
    )


def test_manual_genre_survives_process_all_enrich(managed_root, monkeypatch):
    track_id = _seed_track(managed_root, "song.mp3", artist="Some Artist", title="A Title", genre="")
    workspace_service.edit_inbox_track_metadata(managed_root, track_id, genre="My Deliberate Genre")

    from backend.app.services import provider_routing_service, consensus_service

    class _FieldConsensus:
        def __init__(self, value, confidence):
            self.value = value
            self.confidence = confidence
            self.reason_code = "matched"
            self.evidence = []

    class _Consensus:
        fields = {
            "artist": _FieldConsensus(None, "LOW"),
            "title": _FieldConsensus(None, "LOW"),
            "genre": _FieldConsensus("Some Provider Genre", "HIGH"),
        }

    monkeypatch.setattr(provider_routing_service, "gather_evidence", lambda *a, **k: {})
    monkeypatch.setattr(consensus_service, "build_track_consensus", lambda *a, **k: _Consensus())

    preparation_service.enrich_tracks(managed_root, [track_id])

    assert _row(managed_root, track_id)["genre"] == "My Deliberate Genre", (
        "a manually-entered non-empty, non-junk Genre must survive Process All's enrichment stage"
    )
