"""
Targeted tests for backend.app.services.tag_write_service (Cycle 7:
controlled metadata write-back).

These tests mutate REAL disposable audio fixtures generated by ffmpeg --
never anything under /home/paak/Music/crateiq-test-library. Every fixture
lives under pytest's tmp_path and is discarded after the test.

TAG_WRITE_BACKUP_DIR and JOBS_DB_PATH are monkeypatched per test so no test
run ever writes into this repo's real backend/data/ directory.
"""
from __future__ import annotations

import shutil
import sqlite3
import subprocess
from pathlib import Path

import pytest

from backend.app.core import db as backend_db
from backend.app.services import tag_write_service as svc

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not available")


def _make_audio(path: Path, fmt: str = "mp3") -> None:
    codec = ["-c:a", "libmp3lame", "-b:a", "32k"] if fmt == "mp3" else ["-c:a", "flac"]
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono", "-t", "1", *codec, str(path)],
        check=True,
    )


def _write_tags(path: Path, **tags: str) -> None:
    from mutagen import File as MFile
    audio = MFile(str(path), easy=True)
    for key, value in tags.items():
        if value:
            audio[key] = [value]
    audio.save()


def _read_tags(path: Path) -> dict[str, str]:
    from mutagen import File as MFile
    audio = MFile(str(path), easy=True)
    get = lambda k: (audio.get(k) or [""])[0]
    return {k: get(k) for k in ("artist", "title", "album", "genre", "composer")}


@pytest.fixture()
def env(tmp_path, monkeypatch):
    root = tmp_path / "library_root"
    (root / "library").mkdir(parents=True)
    monkeypatch.setenv("CRATEIQ_LIBRARY_ROOT", str(root))
    monkeypatch.setattr(backend_db, "JOBS_DB_PATH", tmp_path / "jobs.db")
    backend_db.init_db()
    monkeypatch.setattr(svc, "TAG_WRITE_BACKUP_DIR", tmp_path / "tag_write_backups")

    db_path = root / "logs" / "processed.db"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.execute(
        "CREATE TABLE tracks (id INTEGER PRIMARY KEY AUTOINCREMENT, filepath TEXT NOT NULL UNIQUE, "
        "filename TEXT NOT NULL, artist TEXT, title TEXT, album TEXT, genre TEXT)"
    )
    conn.commit()
    conn.close()
    return root


def _insert_track(root: Path, *, filepath: Path, artist=None, title=None, album=None, genre=None) -> int:
    with sqlite3.connect(root / "logs" / "processed.db") as conn:
        cursor = conn.execute(
            "INSERT INTO tracks (filepath, filename, artist, title, album, genre) VALUES (?, ?, ?, ?, ?, ?)",
            (str(filepath), filepath.name, artist, title, album, genre),
        )
        return cursor.lastrowid


def test_build_plan_computes_exact_diff_and_is_side_effect_free(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    _write_tags(path, artist="Old Artist", title="Same Title", composer="Keep Me")
    track_id = _insert_track(root, filepath=path, artist="New Artist", title="Same Title", genre="House")

    original_bytes = path.read_bytes()
    plan = svc.build_plan([track_id])

    item = plan["items"][0]
    assert item["blocked"] is False
    fields = {f["field"]: f for f in item["fields"]}
    assert fields["artist"] == {"field": "artist", "current_file_value": "Old Artist", "approved_value": "New Artist", "action": "REPLACE"}
    assert fields["genre"] == {"field": "genre", "current_file_value": None, "approved_value": "House", "action": "ADD"}
    assert "title" not in fields, "identical value must never appear as a planned change"
    assert plan["additions"] == 1 and plan["replacements"] == 1
    assert path.read_bytes() == original_bytes, "preview must never touch the file"


def test_build_plan_expected_mtime_ns_is_a_string(env):
    """
    Regression: nanosecond epoch timestamps exceed Number.MAX_SAFE_INTEGER,
    so a JS client that round-trips expected_mtime_ns as a JSON *number*
    silently corrupts it, permanently failing apply_plan's staleness check
    for every real browser-driven write. It must be serialized as a string.
    """
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    track_id = _insert_track(root, filepath=path, artist="New Artist")

    item = svc.build_plan([track_id])["items"][0]

    assert isinstance(item["expected_mtime_ns"], str)
    assert int(item["expected_mtime_ns"]) == path.stat().st_mtime_ns


def test_apply_accepts_expected_mtime_ns_as_string(env):
    """apply_plan must accept the string form echoed back by a JSON client."""
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    track_id = _insert_track(root, filepath=path, artist="New Artist")

    item = svc.build_plan([track_id])["items"][0]
    expected = {track_id: {"expected_size": item["expected_size"], "expected_mtime_ns": item["expected_mtime_ns"]}}

    result = svc.apply_plan([track_id], expected, confirm=True)

    assert result["applied"] == 1 and result["failed"] == 0


def test_build_plan_blocks_unsupported_format_and_missing_file(env):
    root = env
    wav_path = root / "library" / "track.wav"
    wav_path.write_bytes(b"not-really-audio-but-unsupported-anyway")
    wav_id = _insert_track(root, filepath=wav_path, artist="X")

    missing_path = root / "library" / "gone.mp3"
    missing_id = _insert_track(root, filepath=missing_path, artist="X")

    plan = svc.build_plan([wav_id, missing_id])
    by_id = {item["track_id"]: item for item in plan["items"]}
    assert by_id[wav_id]["blocked"] is True and "WAV" in by_id[wav_id]["blocker"]
    assert by_id[missing_id]["blocked"] is True and "no longer exists" in by_id[missing_id]["blocker"]
    assert plan["blocked_count"] == 2


def test_apply_requires_confirm(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    track_id = _insert_track(root, filepath=path, artist="New")
    with pytest.raises(ValueError, match="confirm=true"):
        svc.apply_plan([track_id], {}, confirm=False)


def test_apply_writes_only_approved_fields_preserves_unrelated_tags_and_audio(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    _write_tags(path, artist="Old Artist", title="Keep This Title", composer="Untouched Composer")
    track_id = _insert_track(root, filepath=path, artist="New Artist", title="Keep This Title", genre="Afro House")

    plan = svc.build_plan([track_id])
    item = plan["items"][0]
    expected = {track_id: {"expected_size": item["expected_size"], "expected_mtime_ns": item["expected_mtime_ns"]}}
    original_backup_source_bytes = path.read_bytes()

    result = svc.apply_plan([track_id], expected, confirm=True)

    assert result["status"] == "completed"
    assert result["applied"] == 1 and result["failed"] == 0
    tags = _read_tags(path)
    assert tags["artist"] == "New Artist"
    assert tags["genre"] == "Afro House"
    assert tags["title"] == "Keep This Title", "field with no diff must be left alone"
    assert tags["composer"] == "Untouched Composer", "unrelated tag must survive a write-back"

    from mutagen import File as MFile
    assert MFile(str(path)).info.length == pytest.approx(1.0, abs=0.2), "audio stream itself must be unaffected"

    operation = svc.get_operation(result["operation_id"])
    assert operation["status"] == "completed"
    manifest = operation["backup_manifest"][0]
    backup_path = svc.TAG_WRITE_BACKUP_DIR / result["operation_id"] / manifest["backup_filename"]
    assert backup_path.is_file()
    assert backup_path.read_bytes() == original_backup_source_bytes, "backup must be byte-for-byte the pre-write file"
    assert svc._sha256(backup_path) == manifest["original_sha256"]


def test_apply_blocks_stale_file_changed_since_preview(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    _write_tags(path, artist="Old Artist")
    track_id = _insert_track(root, filepath=path, artist="New Artist")

    plan = svc.build_plan([track_id])
    item = plan["items"][0]
    stale_expected = {track_id: {"expected_size": item["expected_size"] + 999, "expected_mtime_ns": item["expected_mtime_ns"]}}

    result = svc.apply_plan([track_id], stale_expected, confirm=True)

    assert result["failed"] == 1 and result["applied"] == 0
    assert "stale" in result["results"][0]["reason"].lower()
    assert _read_tags(path)["artist"] == "Old Artist", "a stale-blocked file must never be written"
    operation = svc.get_operation(result["operation_id"])
    assert operation["backup_manifest"] == [], "no backup should be created for a file blocked as stale"


def test_apply_skips_tracks_with_no_diff_without_creating_backup(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    _write_tags(path, artist="Same Artist")
    track_id = _insert_track(root, filepath=path, artist="Same Artist")

    plan = svc.build_plan([track_id])
    item = plan["items"][0]
    expected = {track_id: {"expected_size": item["expected_size"], "expected_mtime_ns": item["expected_mtime_ns"]}}

    result = svc.apply_plan([track_id], expected, confirm=True)

    assert result["skipped"] == 1 and result["applied"] == 0
    operation = svc.get_operation(result["operation_id"])
    assert operation["backup_manifest"] == []


def test_restore_reverts_file_to_byte_identical_backup(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    _write_tags(path, artist="Original Artist", title="Original Title")
    original_bytes = path.read_bytes()
    track_id = _insert_track(root, filepath=path, artist="Changed Artist", title="Original Title")

    plan = svc.build_plan([track_id])
    item = plan["items"][0]
    expected = {track_id: {"expected_size": item["expected_size"], "expected_mtime_ns": item["expected_mtime_ns"]}}
    result = svc.apply_plan([track_id], expected, confirm=True)
    assert result["applied"] == 1
    assert path.read_bytes() != original_bytes, "sanity: the write actually changed the file"

    restore_result = svc.restore_file(result["operation_id"], track_id, confirm=True)

    assert restore_result["restored"] is True and restore_result["verified"] is True
    assert path.read_bytes() == original_bytes, "restored file must be byte-identical to the pre-write original"
    operation = svc.get_operation(result["operation_id"])
    assert operation["status"] == "restored"


def test_restore_requires_confirm_and_valid_operation(env):
    with pytest.raises(ValueError, match="confirm=true"):
        svc.restore_file("does-not-matter", 1, confirm=False)
    with pytest.raises(LookupError):
        svc.restore_file("nonexistent-operation-id", 1, confirm=True)


def test_recover_interrupted_operations_marks_running_as_failed(env):
    root = env
    path = root / "library" / "track.mp3"
    _make_audio(path)
    track_id = _insert_track(root, filepath=path, artist="X")
    from backend.app.core.db import get_conn
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO tag_write_operations (id, status, track_count, created_at, started_at) VALUES ('stuck-op', 'running', 1, '2026-01-01', '2026-01-01')"
        )

    recovered = svc.recover_interrupted_operations()

    assert recovered == 1
    operation = svc.get_operation("stuck-op")
    assert operation["status"] == "failed"
    assert operation["error_reason"] == "backend_restarted"
